{{ if .Values.mysql.enabled  }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-{{ .Values.enviroment }}
spec:
  selector:
    matchLabels:
      app: mysql-{{ .Values.enviroment }}
  serviceName: "mysql-{{ .Values.enviroment }}"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-{{ .Values.enviroment }}
    spec:
      containers:
        - image: mysql:8
          name: mysql-{{ .Values.enviroment }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: MYSQL_DATABASE
            value: django
          ports:
          - containerPort: 3306
            name: mysql            
          volumeMounts:
          - name: mysql-pvc-{{ .Values.enviroment }}
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc-{{ .Values.enviroment }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.mysql.storagesize | default "5" }}Gi
      storageClassName: do-block-storage-retain
{{ end }}