apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
  labels:
    app.kubernetes.io/name: {{ .Values.appname }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appname }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appname }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.imagePort }}
        env:
            - name: DEBUG
              value: {{ .Values.envar.debug | quote }}
            - name: ALLOWED_HOST
              value: {{ .Values.envar.host }}
            - name: STATIC_ROOT
              value: 'True'