apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.appname }}
  annotations:
    cert-manager.io/issuer: {{ .Values.issuerSecretName }}
spec:
  rules:
    - host: {{ .Values.envar.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appname }}-service
                port:
                  number: 80
  tls:
  - hosts:
    - {{ .Values.envar.host }}
    secretName: {{ .Values.issuerSecretName }}

  ingressClassName: nginx