apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.appname }}
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: {{ .Values.imagePort }}