enviroment: dev
appname: djangoproject
deploymentname: djangoproject-deployment
image: registry.digitalocean.com/erikregistry/djangoproject:9e1aa98
imagePort: 5000

issuerSecretName: letsencrypt-nginx
envar:
    debug: 'True'
    host: dev.haltlair.se
    
