enviroment: prod
appname: djangoproject
deploymentname: djangoproject-deployment
image: registry.digitalocean.com/erikregistry/djangoproject:latest
imagePort: 5000

issuerSecretName: letsencryptit-nginx
envar:
    debug: 'False'
    host: haltlair.se
    