enviroment: prod
appname: djangoproject
deploymentname: djangoproject-deployment
image: registry.digitalocean.com/erikregistry/djangoproject:73f78cd-prod
imagePort: 5000

issuerSecretName: letsencryptit-nginx
envar:
    debug: 'True'  #QuickFix should be false
    host: haltlair.se
    
