enviroment: prod
appname: djangoproject
deploymentname: djangoproject-deployment
image: registry.digitalocean.com/erikregistry/djangoproject:b9db6ea
imagePort: 5000

issuerSecretName: letsencryptit-nginx
envar:
    debug: 'True' 
    host: haltlair.se


phpmyadmin:
    fullnameOverride: "phpmyadmin"
    db.host: mysql
    enabled: true
    host: db.haltlair.se

mysql:
    enabled: true
    host: true
    storagesize: 15
