enviroment: dev
appname: djangoproject
deploymentname: djangoproject-deployment
image: registry.digitalocean.com/erikregistry/djangoproject:b9db6ea
imagePort: 5000

issuerSecretName: letsencrypt-nginx
envar:
    debug: 'True'
    host: dev.haltlair.se


phpmyadmin:
    fullnameOverride: "phpmyadmin"
    db.host: mysql
    enabled: true
    host: devdb.haltlair.se

mysql:
    enabled: true
    host: true

