enviroment: prod
appname: djangoproject
deploymentname: djangoproject-deployment
image: registry.digitalocean.com/erikregistry/djangoproject:b9db6ea
imagePort: 5000

issuerSecretName: letsencryptit-nginx
envar:
    debug: 'True'  #QuickFix should be false
    host: haltlair.se
    