name: dev image deploy

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

env:
  PROJECT_NAME: djangoproject
  TAG: latest #$(git rev-parse --short "$GITHUB_SHA")
  DEPLOYMENT_NAME: djangoproject-deployment
  NAMESPACE: dev
jobs:
  build_push_image:
    name: build push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build image 
        run: docker build -t python-docker .

## Pushing to docker hub

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}

      - name: Tag image 
        run:
          docker tag python-docker erikhalt/${{ env.PROJECT_NAME }}:${{ env.TAG }}
      
      - name: Push image to Dokcerhub Registry 
        run: docker push erikhalt/${{ env.PROJECT_NAME }}:${{ env.TAG }}
      
## Pushing to DO

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_KEY }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag image 
        run:
          docker tag python-docker registry.digitalocean.com/erikregistry/${{ env.PROJECT_NAME }}:${{ env.TAG }}
      
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/erikregistry/${{ env.PROJECT_NAME }}:${{ env.TAG }}

  kill_stuff:
    name: restart deployment
    runs-on: ubuntu-latest
    needs: build_push_image
    steps:
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_KEY }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 clustermedrasmus

      - name: Set kubernetes namespace
        run: kubectl config set-context --current --namespace=${{ env.NAMESPACE }}
        env:
          NAMESPACE: ${{ env.NAMESPACE }}

      - name: Verify deployment
        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
        env:
          NAMESPACE: ${{ env.NAMESPACE }}
 
