name: prod image deploy

on:
  release:
    types: [published]
    branches:
      - 'main'
  

env:
  PROJECT_NAME: djangoproject
  DEPLOYMENT_NAME: djangoproject-deployment
  NAMESPACE: prod
jobs:
  deploy_the_thing:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_KEY }}


      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 clustermedrasmus


      - name: Install Helmchart
        uses: azure/setup-helm@v3

      - name: Helm dependency update   
        run: helm dependency update helm/ -n $NAMESPACE
        env:
          NAMESPACE: ${{ inputs.namespaces }}

      - name: Set kubernetes namespace
        run: kubectl config set-context --current --namespace=$NAMESPACE
        env:
          NAMESPACE: ${{ inputs.namespaces }} 
         
      - name: Generate Kubernetes manifest from Helmchart
        run: helm template helm -f helm/values.${{ env.NAMESPACE }}.yaml > out.yaml
        env:
          NAMESPACE: ${{ env.NAMESPACE }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f out.yaml -n ${{ env.NAMESPACE }}
        env:
          NAMESPACE: ${{ env.NAMESPACE }}


      - name: Verify deployment
        run: kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
        env:
          NAMESPACE: ${{ env.NAMESPACE }}
